import prato1 from "../../../assets/arroz.png";
import prato2 from "../../../assets/arroz.png";
import prato3 from "../../../assets/arroz.png";
import prato4 from "../../../assets/arroz.png";

const hoje = new Date().toLocaleDateString("pt-BR");

export const pratosMock = [
  {
    id: "0001",
    nome: "Arroz com Feijão",
    categoria: "Prato Principal",
    descricao: "Arroz fresquinho com feijão carioca, servido com carne de frango.",
    compra: "R$ 10,00",
    venda: "R$ 12,00",
    preco: "R$ 12,00",
    estoque: 100,
    status: "ativo",
    registro: hoje,
    imagem: prato1,
  },
  {
    id: "0002",
    nome: "Espaguete à Bolonhesa",
    categoria: "Prato Principal",
    descricao: "Macarrão espaguete com molho bolonhesa à base de carne moída e tomate.",
    compra: "R$ 15,00",
    venda: "R$ 18,00",
    preco: "R$ 18,00",
    estoque: 50,
    status: "ativo",
    registro: hoje,
    imagem: prato2,
  },
  {
    id: "0003",
    nome: "Feijoada Completa",
    categoria: "Prato Principal",
    descricao: "Feijoada tradicional com arroz, couve, laranja e farofa.",
    compra: "R$ 18,00",
    venda: "R$ 22,00",
    preco: "R$ 22,00",
    estoque: 30,
    status: "ativo",
    registro: hoje,
    imagem: prato3,
  },
  {
    id: "0004",
    nome: "Salada Caesar",
    categoria: "Entrada",
    descricao: "Salada com alface, frango grelhado, queijo parmesão e molho Caesar.",
    compra: "R$ 12,00",
    venda: "R$ 15,00",
    preco: "R$ 15,00",
    estoque: 80,
    status: "ativo",
    registro: hoje,
    imagem: prato4,
  },
  {
    id: "0005",
    nome: "Sopa de Abóbora",
    categoria: "Entrada",
    descricao: "Sopa cremosa de abóbora com temperos especiais.",
    compra: "R$ 7,00",
    venda: "R$ 10,00",
    preco: "R$ 10,00",
    estoque: 60,
    status: "inativo",
    registro: hoje,
    imagem: "https://example.com/sopa-abobora.jpg",
  },
  {
    id: "0006",
    nome: "Tiramisu",
    categoria: "Sobremesa",
    descricao: "Sobremesa italiana à base de café, creme de mascarpone e cacau.",
    compra: "R$ 5,00",
    venda: "R$ 8,00",
    preco: "R$ 8,00",
    estoque: 40,
    status: "ativo",
    registro: hoje,
    imagem: "https://example.com/tiramisu.jpg",
  },
  {
    id: "0007",
    nome: "Mousse de Maracujá",
    categoria: "Sobremesa",
    descricao: "Mousse cremosa de maracujá com cobertura de geléia de maracujá.",
    compra: "R$ 4,00",
    venda: "R$ 6,00",
    preco: "R$ 6,00",
    estoque: 70,
    status: "ativo",
    registro: hoje,
    imagem: "https://example.com/mousse-maracuja.jpg",
  },
  {
    id: "0008",
    nome: "Churros com Doce de Leite",
    categoria: "Sobremesa",
    descricao: "Churros fresquinhos com recheio de doce de leite e açúcar e canela.",
    compra: "R$ 3,00",
    venda: "R$ 5,00",
    preco: "R$ 5,00",
    estoque: 20,
    status: "inativo",
    registro: hoje,
    imagem: "https://example.com/churros.jpg",
  },
  {
    id: "0009",
    nome: "Bife à Parmegiana",
    categoria: "Prato Principal",
    descricao: "Bife empanado coberto com molho de tomate e queijo derretido.",
    compra: "R$ 20,00",
    venda: "R$ 25,00",
    preco: "R$ 25,00",
    estoque: 50,
    status: "ativo",
    registro: hoje,
    imagem: "https://example.com/bife-parmegiana.jpg",
  },
  {
    id: "0010",
    nome: "Panqueca de Carne",
    categoria: "Prato Principal",
    descricao: "Panqueca recheada com carne moída e molho de tomate.",
    compra: "R$ 14,00",
    venda: "R$ 18,00",
    preco: "R$ 18,00",
    estoque: 70,
    status: "ativo",
    registro: hoje,
    imagem: "https://example.com/panqueca.jpg",
  },
];