export const ROUTERS = {
    HOME: "/",
    LOGIN: "/login",
    ESTOQUE_PRODUTOS: "/estoque",
    FORMULARIO_PRODUTOS: "/estoque/formulario-produtos",
    ESTOQUE_PRATOS: "/pratos",
    FORMULARIO_PRATOS: "/pratos/formulario-pratos",
    ATENDENTE: "/atendente",
    COMANDAS: "/cozinha",
    SETOR_CATEGORIA: "/setor-categoria",
    FUNCIONARIOS: "/funcionarios",
    DASHBOARD: "/dashboard",
    PLANOS_INTERNOS: "/planos-internos",
    UNAUTHORIZED: "/unauthorized",
    REDEFINIR_SENHA: "/redefinir-senha",
}