import arroz from "../../../assets/arroz.png";
const hoje = new Date().toLocaleDateString("pt-BR");

export const produtosMock = [
  {
    id: "0001",
    nome: "Arroz Branco Tipo 1",
    validade: "12/07/2025",
    compra: "R$ 4,50",
    venda: "R$ 6,00",
    estoque: 100,
    registro: hoje,
    descricao:
      "Arroz branco tipo 1, grãos selecionados, ideal para o dia a dia.",
    imagem: arroz,
  },
  {
    id: "0002",
    nome: "Feijão Carioca",
    validade: "15/08/2025",
    compra: "R$ 5,00",
    venda: "R$ 6,50",
    estoque: 80,
    registro: hoje,
    descricao: "Feijão carioca de alta qualidade, saboroso e nutritivo.",
    imagem: arroz,
  },
  {
    id: "0003",
    nome: "Macarrão Espaguete",
    validade: "20/09/2025",
    compra: "R$ 2,00",
    venda: "R$ 3,00",
    estoque: 120,
    registro: hoje,
    descricao:
      "Macarrão espaguete de trigo duro, ideal para diversas receitas.",
    imagem: arroz,
  },
  {
    id: "0004",
    nome: "Leite Integral 1L",
    validade: "10/05/2025",
    compra: "R$ 3,50",
    venda: "R$ 4,50",
    estoque: 200,
    registro: hoje,
    descricao: "Leite integral pasteurizado, fonte de cálcio e vitaminas.",
    imagem: arroz,
  },
  {
    id: "0005",
    nome: "Óleo de Soja 900ml",
    validade: "25/06/2025",
    compra: "R$ 4,00",
    venda: "R$ 5,50",
    estoque: 150,
    registro: hoje,
    descricao:
      "Óleo de soja refinado, ideal para frituras e preparos diversos.",
    imagem: arroz,
  },
  {
    id: "0006",
    nome: "Açúcar Refinado 1kg",
    validade: "30/07/2025",
    compra: "R$ 2,50",
    venda: "R$ 3,50",
    estoque: 90,
    registro: hoje,
    descricao: "Açúcar refinado de alta pureza, ideal para doces e bebidas.",
    imagem: arroz,
  },
  {
    id: "0007",
    nome: "Sal Refinado 1kg",
    validade: "15/08/2025",
    compra: "R$ 1,00",
    venda: "R$ 1,50",
    estoque: 110,
    registro: hoje,
    descricao: "Sal refinado iodado, essencial para o preparo de alimentos.",
    imagem: arroz,
  },
  {
    id: "0008",
    nome: "Café Torrado e Moído 500g",
    validade: "20/09/2025",
    compra: "R$ 8,00",
    venda: "R$ 10,00",
    estoque: 70,
    registro: hoje,
    descricao: "Café torrado e moído, sabor intenso e aroma marcante.",
    imagem: arroz,
  },
  {
    id: "0009",
    nome: "Farinha de Trigo 1kg",
    validade: "10/10/2025",
    compra: "R$ 3,00",
    venda: "R$ 4,00",
    estoque: 130,
    registro: hoje,
    descricao: "Farinha de trigo enriquecida com ferro e ácido fólico.",
    imagem: arroz,
  },
  {
    id: "0010",
    nome: "Manteiga com Sal 200g",
    validade: "05/05/2025",
    compra: "R$ 5,00",
    venda: "R$ 6,50",
    estoque: 60,
    registro: hoje,
    descricao:
      "Manteiga com sal, sabor tradicional, ideal para pães e receitas.",
    imagem: arroz,
  },

  {
    id: "0011",
    nome: "Achocolatado em Pó 400g",
    validade: "10/06/2025",
    compra: "R$ 5,00",
    venda: "R$ 7,00",
    estoque: 0,
    registro: new Date().toLocaleDateString("pt-BR"),
    descricao: "Achocolatado em pó, ideal para bebidas e receitas.",
    imagem: arroz,
  },
  {
    id: "0012",
    nome: "Refrigerante Cola 2L",
    validade: "18/05/2025",
    compra: "R$ 4,00",
    venda: "R$ 6,50",
    estoque: 0,
    registro: new Date().toLocaleDateString("pt-BR"),
    descricao: "Refrigerante sabor cola, embalagem econômica de 2 litros.",
    imagem: arroz,
  },
  {
    id: "0013",
    nome: "Biscoito Recheado Chocolate",
    validade: "01/07/2025",
    compra: "R$ 2,00",
    venda: "R$ 3,00",
    estoque: 0,
    registro: new Date().toLocaleDateString("pt-BR"),
    descricao: "Biscoito recheado sabor chocolate, crocante e delicioso.",
    imagem: arroz,
  },

  {
    id: "0014",
    nome: "Iogurte Natural 170g",
    validade: "28/04/2025",
    compra: "R$ 1,50",
    venda: "R$ 2,50",
    estoque: 5,
    registro: new Date().toLocaleDateString("pt-BR"),
    descricao: "Iogurte natural, ideal para consumo direto ou receitas.",
    imagem: arroz,
  },
  {
    id: "0015",
    nome: "Presunto Fatiado 200g",
    validade: "22/04/2025",
    compra: "R$ 4,00",
    venda: "R$ 5,50",
    estoque: 8,
    registro: new Date().toLocaleDateString("pt-BR"),
    descricao: "Presunto cozido fatiado, pronto para consumo.",
    imagem: arroz,
  },
  {
    id: "0016",
    nome: "Queijo Mussarela 300g",
    validade: "25/04/2025",
    compra: "R$ 6,50",
    venda: "R$ 9,00",
    estoque: 10,
    registro: new Date().toLocaleDateString("pt-BR"),
    descricao: "Queijo mussarela fatiado, sabor leve e derretimento ideal.",
    imagem: arroz,
  },
];
